name: tzdata

on:
  push:

  schedule:
    - cron: '0 0 * * 0'

jobs:
  cmp:
    uses: WaterLemons2k/.github/.github/workflows/compare.yml@main
    with:
      pre: |
        echo 'deb [trusted=yes] http://deb.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list
        sudo apt-get update
      new: $(sudo apt-get install tzdata | awk '/G/ {split($7, a, "-"); print a[1]; exit}')
      artifact-name: tzdata
      artifact-path: /usr/share/zoneinfo

  keep-scheduled-workflow-activity:
    needs: cmp
    if: needs.cmp.outputs.changed == 'false'
    uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1

  tzdata:
    needs: cmp
    if: needs.cmp.outputs.changed == 'true'
    uses: WaterLemons2k/.github/.github/workflows/git.yml@main
    with:
      artifact-name: tzdata
      run: |
        sed -i "3c Version: ${{ needs.cmp.outputs.version }}" README.md
        echo "${{ needs.cmp.outputs.version }}" > VERSION
      commit_message: "feat: bump tzdata to ${{ needs.cmp.outputs.version }}"
      tagging_message: ${{ needs.cmp.outputs.version }}
